### ISSUE TITLE
App crashes on startup due to a parsing JSONException 

### ISSUE THREAD

**Issue by catalinghita8** [Mercandj/android-dev-challenge-compose-4#1]
Stacktrace:
```
2021-07-09 09:52:46.558 10151-10468/com.example.androiddevchallenge E/AndroidRuntime: FATAL EXCEPTION: weather_load
    Process: com.example.androiddevchallenge, PID: 10151
    org.json.JSONException: No value for weather
        at org.json.JSONObject.get(JSONObject.java:400)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595)
        at com.example.androiddevchallenge.weather_api.WeatherApiManagerImpl.getWeather(WeatherApiManagerImpl.kt:49)
        at com.example.androiddevchallenge.weather.WeatherManagerImpl$load$1.run(WeatherManagerImpl.kt:41)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Root cause: Wheather API throws 429.
```
{
  "cod": 429,
  "message": "Your account is temporary blocked due to exceeding of requests limitation of your subscription type. Please choose the proper subscription http://openweathermap.org/price"
}
```

**Comment by Mercandj** [comment]
Nice catch, thks for the detailed issue.

That because I git-versioned my key from the website `openweathermap`. That was great because like that anyone can use the app, but I shouldn't do that.

Indeed, now the key as been banned. So I can either (1) try to find another key either (2) make "clients" of this repo write there own key. I will see, maybe option (2).

**Comment by Mercandj** [comment]
Solution here https://github.com/Mercandj/android-dev-challenge-compose-4/commit/0333d47ed4b21f2f60962308fb3dda5b2b74b212

I removed the key, and display fake data if the key is the fake one (like that people that want to check only the UI are able to do it)
